### ISSUE TITLE
The source code does not work like online demo.

### ISSUE THREAD

**Issue by imaaronzhang** [marmelab/admin-on-rest-demo#7] opened 2017-02-24 12:52 UTC
Clone and start the code on the Windows OS, browse it in Chrome, IE Edge and Firefox.

1. The left sidebar does not work like online demo.  
2. The data grid is not responsive after change the theme to dark.

No error info.

**Comment by fzaninotto** [comment] 2017-02-24 12:54
That's because the current source code uses the `next` branch of admin-on-rest.

Once `next` will be merged into `master` (in about 3 weeks), you'll be able to reproduce the same feature. Until then, I recommend that you use an older version of the demo, e.g. 4f1af6ba9dddfa283169c816a509d0ee41170c19 (sorry, to tags for now).

**Closed as completed by fzaninotto** 2017-02-24 12:54 UTC

**Comment by imaaronzhang** [comment] 2017-02-24 13:10
Thanks for your reply.
