### ISSUE TITLE
Cannot switch from the menu bar

### ISSUE THREAD

**Issue by youknowone** [marmelab/admin-on-rest-demo#6] opened 2017-02-17 08:30 UTC
Once I click a menu on the bar, it is not switchable to another one.

traceback:
```
Uncaught (in promise) Error: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
    at invariant (invariant.js:44)
    at Object.removeComponentAsRefFrom (ReactOwner.js:82)
    at detachRef (ReactRef.js:32)
    at Object.ReactRef.detachRefs (ReactRef.js:84)
    at Object.unmountComponent (ReactReconciler.js:78)
    at ReactCompositeComponentWrapper.unmountComponent (ReactCompositeComponent.js:418)
    at Object.unmountComponent (ReactReconciler.js:79)
    at ReactCompositeComponentWrapper.unmountComponent (ReactCompositeComponent.js:418)
    at Object.unmountComponent (ReactReconciler.js:79)
    at Object.unmountChildren (ReactChildReconciler.js:146)
```

**Comment by fzaninotto** [comment] 2017-02-17 11:25
Can't reproduce this issue. What is your browser?

**Comment by youknowone** [comment] 2017-02-17 11:27
Chrome 56. I have no problem when following your tutorial only with `admin-on-rest`, but only with the demo.

**Comment by fzaninotto** [comment] 2017-02-17 11:46
Still can't reproduce, with the same browser. What's your platform? 

Also, are you using a checkout and a local build, or https://marmelab.com/admin-on-rest-demo/ ?

**Comment by youknowone** [comment] 2017-02-20 01:53
I made a checkout: `git clone https://github.com/marmelab/admin-on-rest-demo`

**Comment by fzaninotto** [comment] 2017-02-21 09:38
Does the problem occur for you in https://marmelab.com/admin-on-rest-demo/ ?

**Comment by youknowone** [comment] 2017-02-22 08:55
No problem there.

**Comment by fzaninotto** [comment] 2017-06-28 21:45
Can't reproduce, it must be due to your code. Closing.

**Closed as completed by fzaninotto** 2017-06-28 21:45 UTC
